[general]
live_config_reload = true

# 起動時にはtmuxのdefault.session.confとかを読み込んで
# あらかじめペイン分割したりしたい
[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t default || tmux new -s default"] }

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 8, y = 4 }
opacity = 0.95

[cursor]
style = "Block"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12.5
offset = { x = 0, y = 2 }
